version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/admin-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/map-client"
    schedule:
      interval: "weekly"
