import type { MapConfig } from '@ogc-maps/storybook-components/types';

export const mapConfig: MapConfig = {
  sources: [
    {
      id: 'tipg-local',
      url: 'http://localhost:8000',
      label: 'Local tipg (Natural Earth)',
      tileMatrixSetId: 'WebMercatorQuad',
    },
  ],
  layers: [
    {
      id: 'countries',
      sourceId: 'tipg-local',
      collection: 'public.ne_110m_admin_0_countries',
      label: 'Countries',
      visible: true,
      dataMode: 'vector-tiles',
      styles: [{
        type: 'fill',
        paint: {
          'fill-color': '#4a90d9',
          'fill-opacity': 0.6,
          'fill-outline-color': '#2c5f8a',
        },
      }],
      legend: {
        entries: [{ label: 'Countries', color: '#4a90d9', shape: 'square' }],
      },
      search: {
        fields: [
          {
            property: 'name',
            label: 'Country Name',
            type: 'text',
            autocomplete: true,
            placeholder: 'Search countries...',
          },
          {
            property: 'continent',
            label: 'Continent',
            type: 'select',
            // options: [
            //   'Africa',
            //   'Antarctica',
            //   'Asia',
            //   'Europe',
            //   'North America',
            //   'Oceania',
            //   'South America',
            // ],
            prefetch: true,
          },
          {
            property: 'economy',
            label: 'Economy',
            type: 'select',
            options: [
              '1. Developed region: G7',
              '2. Developed region: nonG7',
              '3. Emerging region: BRIC',
              '4. Emerging region: MIKT',
              '5. Emerging region: G20',
              '6. Developing region',
              '7. Least developed region',
            ],
          },
          {
            property: 'pop_est',
            label: 'Population',
            type: 'number',
            inputMode: 'input',
            operator: 'gte',
            min: 0,
            max: 1400000000,
            step: 1000000,
          },
          {
            property: 'gdp_md',
            label: 'GDP (millions USD)',
            type: 'number',
            inputMode: 'input',
            operator: 'between',
            min: 0,
            max: 22000000,
            step: 1000,
          },
        ],
      },
      cql2Filter: {
        id: 'countries-query',
        combinator: 'and',
        rules: [
          {
            id: 'pop-rule',
            property: 'pop_est',
            operator: '>=',
            value: { kind: 'parameter', name: 'minPop', label: 'Min Population', inputType: 'number', default: 10000000 },
          },
        ],
        sortby: [{ property: 'pop_est', direction: 'desc' }],
        limit: 50,
      },
    },
    {
      id: 'cities',
      sourceId: 'tipg-local',
      collection: 'public.ne_110m_populated_places',
      label: 'Cities',
      visible: true,
      dataMode: 'geojson',
      styles: [{
        type: 'circle',
        paint: {
          'circle-color': '#e74c3c',
          'circle-radius': 5,
          'circle-opacity': 0.9,
          'circle-stroke-color': '#ffffff',
          'circle-stroke-width': 1,
        },
      }],
      legend: {
        entries: [{ label: 'Cities', color: '#e74c3c', shape: 'circle' }],
      },
      search: {
        fields: [
          {
            property: 'name',
            label: 'City Name',
            type: 'text',
            autocomplete: true,
            prefetch: true,
            placeholder: 'Search cities...',
          },
          {
            property: 'adm0name',
            label: 'Country',
            type: 'text',
            autocomplete: true,
            prefetch: true,
            placeholder: 'Filter by country...',
          },
          {
            property: 'featurecla',
            label: 'Type',
            type: 'select',
            prefetch: true,
            // options: [
            //   'Admin-0 capital',
            //   'Admin-0 capital alt',
            //   'Admin-0 region capital',
            //   'Admin-1 capital',
            //   'Admin-1 region capital',
            //   'Populated place',
            // ],
          },
          {
            property: 'pop_max',
            label: 'Population (max)',
            type: 'number',
            inputMode: 'slider',
            operator: 'gte',
            min: 0,
            max: 36000000,
            step: 100000,
          },
        ],
      },
    },
    {
      id: 'rivers',
      sourceId: 'tipg-local',
      collection: 'public.ne_110m_rivers_lake_centerlines',
      label: 'Rivers',
      visible: true,
      dataMode: 'vector-tiles',
      styles: [{
        type: 'line',
        paint: {
          'line-color': '#00bcd4',
          'line-width': 2,
          'line-opacity': 0.8,
        },
      }],
      legend: {
        entries: [{ label: 'Rivers', color: '#00bcd4', shape: 'line' }],
      },
      search: {
        fields: [
          {
            property: 'name',
            label: 'River Name',
            type: 'text',
            autocomplete: true,
            placeholder: 'Search rivers...',
          },
        ],
      },
    },
  ],
  basemaps: [
    {
      id: 'carto-positron',
      label: 'CARTO Positron',
      url: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    },
    {
      id: 'carto-dark-matter',
      label: 'CARTO Dark Matter',
      url: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
    },
  ],
  ui: {
    showLayerPanel: true,
    showLegend: true,
    showBasemapSwitcher: true,
    showSearchPanel: true,
    showCoordinateDisplay: true,
    showFeatureDetail: true,
    showFeatureTooltip: true,
    showExportButton: true,
    showExportPdf: true,
    showLegendOpacity: false,
    showMeasureTool: false,
    showSelectionTool: true,
    showImageryPanel: false,
    showCompass: true,
    showGlobalSearch: false,
    showScaleBar: false,
    coordinateFormat: 'decimal-degrees',
    controlLayout: 'individual',
    sideMenuToggleCorner: 'top-right',
  },
  initialView: {
    latitude: 0,
    longitude: 0,
    zoom: 2,
    pitch: 0,
    bearing: 0,
  },
};
